name: Test Feature-Branch

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Unit Tests
        run: yarn test:unit
